### ISSUE TITLE
能给个sql文件吗

### ISSUE THREAD

**Issue by 5542111** [whitestarrain/hospital-springboot#1]

**Comment by 5542111** [comment]
带 测试数据的那种

**Comment by whitestarrain** [comment]
@5542111 抱歉，最近没怎么过来看。
在src/test/resources下就有数据库初始化sql。建库和初始化数据都有。
不过mysql存储过程没在这里放着，我之后找找传上来。

**Comment by 5542111** [comment]
> @5542111 抱歉，最近没怎么过来看。
> 在src/test/resources下就有数据库初始化sql。建库和初始化数据都有。
> 不过mysql存储过程没在这里放着，我之后找找传上来。

ok, 主要需要一点测试数据 麻烦了 数据库sql建立文件是有的.  的确是需要 存储过程中的数据 进行一些测试. 麻烦你有空传一下了! 谢谢

**Comment by whitestarrain** [comment]
@5542111 
存储过程我传上去了，src/test/resources/存储过程.sql下。
不过存储过程只是一些业务逻辑。不是数据插入。测试数据的话就在那个src/test/resources/数据库初始化.sql 中。
当时是有一个excel的测试数据，用python搞成了sql，就没使用存储过程自己生成。
